const SIGN_IN = 'SIGN_IN'
const SIGN_OUT = 'SIGN_OUT'
const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
const CHANGE_USER_PHOTO = 'CHANG_USER_PHOTO'
const SET_SYSTEM_LOCK = 'LOCK'
const SET_SYSTEM_UNLOCK = 'UNLOCK'

export {
    SIGN_IN,
    SIGN_OUT,
    CHANGE_USER_NAME,
    CHANGE_USER_PHOTO,
    SET_SYSTEM_LOCK,
    SET_SYSTEM_UNLOCK
}